//Event
export const QUERY_EVENTS = "QUERY_EVENTS";
export const QUERY_CATEGORY = "QUERY_CATEGORY";
export const QUERY_CATEGORY_TYPE = "QUERY_CATEGORY_TYPE";
export const CREATE_EVENT = "CREATE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const CREATE_TICKET = "CREATE_TICKET";
export const QUERY_TRENDING_EVENT = "QUERY_TRENDING_EVENT";
export const QUERY_EXPERIENCE_EVENT = "QUERY_EXPERIENCE_EVENT";
export const QUERY_EVENT_IN_HANOI = "QUERY_EVENT_IN_HANOI";
export const QUERY_SINGLE_EVENT = "QUERY_SINGLE_EVENT";

//Ticket
export const QUERY_TICKET = "QUERY_TICKET";

//Login
export const SIGN_UP = "SIGN_UP";
export const LOG_IN = "LOG_IN";

//LOCAL ACTION
export const SAVE_EVENT_BASIC_INFO = "SAVE_EVENT_BASIC_INFO";
